config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#一般的な処理を一気に設定
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :blogs
  resources :users, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categories

  root 'blogs#index'
#  root 'users#new'

  #管理画面
  get   'posts', to: 'posts#index'

  #カテゴリ管理
  get   'categories', to: 'categories#index'

  # ログイン / ログアウト
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  # ユーザ登録
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # パスワードリセット
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_sign_in!
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def edit
  end

  def update
    if params[:user][:password].empty?                  # 空白文字
      flash.now[:danger] = "パスワードに空文字を指定することはできません。"
      render 'edit'
    elsif @user.update_attributes(user_params)          # パスワード更新
      log_in @user
      flash.now[:success] = "パスワードが再設定されました。"
      redirect_to posts_path
    else
      flash.now[:danger] = "パスワードが不正です。"
      render 'edit' 
    end
  end

  def create
   @user = User.find_by(mail: params[:password_reset][:mail])
   if @user
     @user.create_reset_digest
     @user.send_password_reset_mail
     flash.now[:info] = "パスワードリセットメールが送信されました。"
     redirect_to login_path
   else
     flash.now[:danger] = "メールアドレスが誤っています。"
     render 'new'
   end
  end

 private

 def user_params
   params.require(:user).permit(:password, :password_confirmation)
 end

 # beforeフィルタ
 def get_user
   @user = User.find_by(mail: params[:mail])
 end

 # 有効なユーザーかどうか確認する
 def valid_user
   unless (@user && @user.activated? &&
           @user.authenticated?(:reset, params[:id]))
     redirect_to root_url
   end
 end

 # トークンが期限切れかどうか確認する
 def check_expiration
   if @user.password_reset_expired?
     flash[:danger] = "パスワード再設定の有効期限が切れています。"
     redirect_to new_password_reset_url
   end
 end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.slim
article class="tech-article"
  - provide(:title, 'Reset password')
  h1 パスワード再設定
  .form-group
    = form_for(@user, url: password_reset_path(params[:id])) do |f|
      = render 'shared/error_messages'
      = hidden_field_tag :mail, @user.mail
      = f.label 'パスワード'
      = f.password_field :password, class: 'form-control'
      = f.label 'パスワード確認'
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "パスワードを更新する"

app/views/password_resets/new.html.slim
article class="tech-article"
  - provide(:title, "Forgot password")
  h1 パスワード再設定
  .form-group
    = form_for(:password_reset, url: password_resets_path) do |f|
      = f.label 'メールアドレス'
      = f.email_field :mail, class: 'form-control'

      - flash.each do |key, value|
        = content_tag :div, value, class: "error"

      = f.submit '送信'