config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#一般的な処理を一気に設定
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :blogs
  resources :users, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categories

  root 'blogs#index'
#  root 'users#new'

  #管理画面
  get   'posts', to: 'posts#index'

  #カテゴリ管理
  get   'categories', to: 'categories#index'

  # ログイン / ログアウト
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  # ユーザ登録
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # パスワードリセット
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable_on :tags
  acts_as_taggable
  has_many :comments, dependent: :destroy
  mount_uploaders :image, ImageUploader
  # @post.commnets
  validates :title, presence: true , length:{minimum:3, message: 'Too short to post!'}
  validates :body, presence: true
  validates :category_id, presence: true

  # カテゴリIDによる絞り込み
  scope :get_by_category_id, ->(category_id, published = nil){
    published ? where(category_id: category_id).where(published: published) : where(category_id: category_id)
  }


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # blog一覧表示
  def index

    #作成日の降順で表示
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(PER)
    if params[:category_id].present?
      @posts = Post.get_by_category_id(params[:category_id]).page(params[:page]).per(PER)
    end

  end

  # 詳細画面表示
  def show
    @post = Post.find(params[:id])
  end

  # 新規作成画面表示
  def new
    @post = Post.new
  end

  # 記事追加
  def create
    # render plain: params[:post].inspect
    # save
    @post = Post.new(post_params)
    if @post.save
      # redirect
      redirect_to posts_path
    else
      # render plain: @post.errors.inspect
      flash.now[:danger] = t('.flash.input_error')
      render 'new'
    end
  end

  # 編集画面表示
  def edit
    @post = Post.find(params[:id])
  end

  # 更新処理
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path #一覧に戻る
    else
      flash.now[:danger] = t('.flash.input_error')
      render 'edit'
    end
  end

  # 削除処理
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path #一覧に戻る
  end



  private
    def post_params
      # strong parameter : パラメータを強めにチェックする
      params.require(:post).permit(:category_id,
        :title,
        :tag_list,
        :body,
        :published,
        {image: []})
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for @post do |f|
  p
    = f.collection_select(:category_id, Category.all, :id, :name,
    :selected => @post.category_id,
    :include_blank => 'カテゴリを選択してください')
    - if@post.errors.messages[:category_id].any?
      span.error= @post.errors.full_messages_for(:category_id)[0]
  p
    = f.text_field :title,placeholder: 'タイトルを入力してください'
    - if@post.errors.messages[:title].any?
      span.error= @post.errors.full_messages_for(:title)[0]
  p
    | ※複数タグをカンマ区切りで入力できます。
    = text_field_tag 'post[tag_list]', @post.tag_list.join(',')
  p
  #editor
    | ※マークダウンが使えます。
    textarea#n.form-control debounce="50" name="post[body]" placeholder="記事内容を入力してください" rows="20" v-model="input" = @post.body
    | プレビュー
    .preview
      div  v-html=("input | marked")
    - if@post.errors.messages[:body].any?
      span.error= @post.errors.full_messages_for(:body)[0]
  br/
  p
    label.checkbox-inline
      = f.check_box :published,{},checked_value = "1", unchecked_value = "0"
      | 公開
  p
    = f.submit
javascript:
   $(document).ready(function(){
     new Vue({
       el: '#editor',
       data: {
         input: '#{j @post.body}',
       },
       filters: {
         marked: marked,
       },
     });
   });
   $('#post_category_id').change(function(){
    var tag = $('#post_tag_list');
    if (tag.val() !=='') {
      tag.val(tag.val() + ',');
    }
    tag.val(tag.val() + $('option:selected').text());
   });

app/views/posts/edit.html.slim
article.tech-article
  = render 'shared/error_messages'
  h1 記事編集
  = render 'form'

app/views/posts/index.html.slim
article class="tech-article"
  h1 過去の記事一覧

  ul
    = form_tag(posts_path, method: "get") do
      = select_tag( :category_id,
        options_from_collection_for_select(Category.all, :id, :name, params[:category_id].to_i),
        :include_blank => 'カテゴリを選択してください')
      = submit_tag "絞り込み"
  ul
    - @posts.each do |post|
      h1[class='tech-article__title']
        = link_to post.title, post_path(post)
        = link_to ' [Edit]', edit_post_path(post), class: 'command'
        = link_to ' [x]', post_path(post), method: :delete,  class: 'command',  data:{ confirm: '削除しますか?'}
        - post.published == 1 ? pub='(公開中)' : pub='(未公開)'
        = ' ' + pub
      .tech-article__date
        = date_format(post.updated_at)

  = paginate @posts

app/views/posts/new.html.slim
article.tech-article
  = render 'shared/error_messages'
  h1 新規投稿
  = render 'form'

app/views/posts/show.html.slim
article.tech-article
  h2.tech-article__title= @post.title
  .tech-article__body
    = markdown(@post.body).html_safe
  = link_to '戻る', :back