config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#一般的な処理を一気に設定
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :blogs
  resources :users, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categories

  root 'blogs#index'
#  root 'users#new'

  #管理画面
  get   'posts', to: 'posts#index'

  #カテゴリ管理
  get   'categories', to: 'categories#index'

  # ログイン / ログアウト
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  # ユーザ登録
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # パスワードリセット
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post
  mount_uploader :image, ImageUploader
  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # カテゴリ一覧表示
  def index
    #作成日の降順で表示
    @categories_list = Category.all.order(created_at: :desc).page(params[:page]).per(PER)
  end

  # 新規作成画面表示
  def new
    @category = Category.new
  end

  # カテゴリ追加
  def create
    @category = Category.new(category_params)
    if @category.save
      # redirect
      redirect_to categories_path
    else
      # render plain: @post.errors.inspect
      render 'new'
    end
  end

  # 編集画面表示
  def edit
    @category = Category.find(params[:id])
  end

  # 更新処理
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path #一覧に戻る
    else
      render 'edit'
    end
  end

  # 削除処理
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  rescue ActiveRecord::InvalidForeignKey
    flash[:danger] = @category.name + 'は記事が存在するため削除できません。'
  ensure
    redirect_to categories_path #一覧に戻る
  end

  private
    def category_params
      # strong parameter : パラメータを強めにチェックする
      params.require(:category).permit(:name,:image)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  .form-group
    = f.label :name, 'カテゴリ名'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :image, 'アイコン画像 ＜現在登録されている画像＞'
    - if @category.image.blank?
      | なし
    - else
      = image_tag @category.image.url, size: '100x100'
  .form-group
    = f.label :image, '新しいアイコン画像'
    = f.file_field :image
    #preview style="max-width:100px"
  .al-c= f.submit
javascript:
   function Filepreview(evt){
    var files = evt.target.files;

   document.getElementById('preview').innerHTML =""

    for(var i = 0; i < 3;i++){
    var reader = new FileReader();
    var f = files[i]
    reader.onload = (function(){
    return function(e) {
    var span = document.createElement('span');
    span.innerHTML= "<img src='" +e.target.result + "'>";
    document.getElementById('preview').insertBefore(span,null);
    };
    })(f);
    reader.readAsDataURL(f);
    }
   }
   document.getElementById('category_image').addEventListener('change',Filepreview,false);

app/views/categories/edit.html.slim
article.tech-article
  h1 カテゴリ編集
  = render 'form'

app/views/categories/index.html.slim
article class="tech-article"
  = render 'shared/error_messages'
  h1 カテゴリ一覧
  = button_to "新規作成", {:action => "new"} ,method: :get
  ul
    - @categories_list.each do |c|
      h1[class='tech-article__title']
        span =c.name+' '
        = link_to '[Edit]', edit_category_path(c), class: 'command'
        = link_to '[x]', category_path(c), method: :delete,  class: 'command',  data:{ confirm: '削除しますか?'}
  = paginate @categories_list

app/views/categories/new.html.slim
article.tech-article
  h1 新規カテゴリ
  = render 'form'