config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#一般的な処理を一気に設定
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :blogs
  resources :users, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categories

  root 'blogs#index'
#  root 'users#new'

  #管理画面
  get   'posts', to: 'posts#index'

  #カテゴリ管理
  get   'categories', to: 'categories#index'

  # ログイン / ログアウト
  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'

  # ユーザ登録
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # パスワードリセット
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/views/layouts/_header.html.slim
/! Sample menu definition
ul#main-menu.sm.sm-clean
  li= link_to '新規投稿', new_post_path
  li= link_to '過去の記事', posts_path
  li= link_to 'カテゴリ管理', categories_path
  li= link_to 'プロフィール修正', edit_user_path(@current_user)
  li= link_to 'ログアウト', logout_path,method: :delete, data:{confirm: 'ログアウトしてもよろしいですか？'}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Myblog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .tech
      section.tech__menu
        .tech__menu__inner
          nav
            ul
              li.home
                a href="/"
                  span.text Myblog.jp
                  button.close.toggle-menu name="button" type="submit"  x
              - if @categories.present?  #カテゴリがある時表示
                - @categories.each do |category|
                  li
                    = link_to blogs_path(category_id: category.id) do
                      = image_tag category.image.url, class: 'icon'
                      span.text= category.name
      section.tech__main
        section.tech__main__header
          - if controller.controller_name == "blogs"
            button.toggle-menu.show-menu name="menu" type="submit"  MENU
          - if controller.controller_name.in?(["posts","categories"]) || (controller.controller_name=="users" && controller.action_name == "edit")
            = render 'layouts/header'
        section.tech__main__inner
          .tech__main__inner__content
            = yield
          .tech__main__inner__side
        - if controller.controller_name == "blogs"
          = render 'footer'